### ISSUE TITLE
Using both start-time and end-time

### ISSUE THREAD

**Issue by drugoi** [siddii/angular-timer#312]
Hello everyone.
I want to use angular-timer as countdown to end-time with external start-time that I get from server (serverTime). 
It is possible with angular-timer?

**Comment by shivenigma** [comment]
you need to have two divs with two individual angular timers inside them and switch them based on whether the countdown is from futuer or count up from past. You need to have two timers with ng-if

**Comment by drugoi** [comment]
@shivenigma probably you don't understand my question properly.
My task is:
Countdown to end-time, but between start-time and end-time, not between current time of OS and end-time.
Maybe I did not completely understand your answer, can you please explain it?

**Comment by shivenigma** [comment]
Are you asking you need to countdown to a specific time from a specific time? I think I got your question wrong. 
As far as I know this plugin does not offer that kind of functionality. But I hope you can modify the source and run the timer from the given date instead of current time. It shouldn't be a more that couple of hours job as I guess. @drugoi
